"""chatroomとmessageをmatching_id/chatroom_idベースに再設計

Revision ID: 0be0524b45c5
Revises: 48d564475d48
Create Date: 2026-07-26 14:53:03.767683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0be0524b45c5'
down_revision: Union[str, Sequence[str], None] = '48d564475d48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatrooms', sa.Column('matching_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'chatrooms', ['matching_id'])
    op.create_foreign_key(None, 'chatrooms', 'matchings', ['matching_id'], ['id'])
    op.drop_column('chatrooms', 'user_id2')
    op.drop_column('chatrooms', 'user_id1')
    op.drop_column('chatrooms', 'chatroom_id')
    op.add_column('messages', sa.Column('chatroom_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('messages_receiver_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chatrooms', ['chatroom_id'], ['id'])
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_receiver_id_fkey'), 'messages', 'users', ['receiver_id'], ['id'])
    op.drop_column('messages', 'chatroom_id')
    op.add_column('chatrooms', sa.Column('chatroom_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chatrooms', sa.Column('user_id1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chatrooms', sa.Column('user_id2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'chatrooms', type_='foreignkey')
    op.drop_constraint(None, 'chatrooms', type_='unique')
    op.drop_column('chatrooms', 'matching_id')
    # ### end Alembic commands ###
