"""add created_at to matchings

Revision ID: 11471f0b313a
Revises: ac976a3c4bbd
Create Date: 2026-06-07 07:04:56.298561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11471f0b313a'
down_revision: Union[str, Sequence[str], None] = 'ac976a3c4bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchings', sa.Column('user_id2', sa.Integer(), nullable=True))
    op.drop_column('matchings', 'User_id2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchings', sa.Column('User_id2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('matchings', 'user_id2')
    # ### end Alembic commands ###
