"""add phone to matchings

Revision ID: 210c533ee439
Revises: 2fb9a7521f00
Create Date: 2026-06-14 04:54:28.277963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210c533ee439'
down_revision: Union[str, Sequence[str], None] = '2fb9a7521f00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matchings', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matchings', 'created_at')
    # ### end Alembic commands ###
