"""add hashed_password to users

Revision ID: 583133caba65
Revises: 48865f207ba6
Create Date: 2026-07-12 03:14:19.997229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '583133caba65'
down_revision: Union[str, Sequence[str], None] = '48865f207ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
