"""messagesをreceiver_idベースに戻す（教材の片思い型に合わせる）

Revision ID: 8a6257f5ce37
Revises: 0be0524b45c5
Create Date: 2026-08-02 02:12:13.704187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6257f5ce37'
down_revision: Union[str, Sequence[str], None] = '0be0524b45c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('messages_chatroom_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'])
    op.drop_column('messages', 'chatroom_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('chatroom_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_chatroom_id_fkey'), 'messages', 'chatrooms', ['chatroom_id'], ['id'])
    op.drop_column('messages', 'receiver_id')
    # ### end Alembic commands ###
