"""create maching table

Revision ID: ac976a3c4bbd
Revises: 3908f5f53601
Create Date: 2026-06-07 06:34:00.930475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac976a3c4bbd'
down_revision: Union[str, Sequence[str], None] = '3908f5f53601'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matchings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id1', sa.Integer(), nullable=True),
    sa.Column('User_id2', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchings_id'), 'matchings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matchings_id'), table_name='matchings')
    op.drop_table('matchings')
    # ### end Alembic commands ###
