"""add phone to chatroom

Revision ID: d9bd627c18dd
Revises: fc96b3518c9d
Create Date: 2026-06-14 01:12:48.205492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9bd627c18dd'
down_revision: Union[str, Sequence[str], None] = 'fc96b3518c9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id1', sa.Integer(), nullable=True),
    sa.Column('matching_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatroom_id'), 'chatroom', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatroom_id'), table_name='chatroom')
    op.drop_table('chatroom')
    # ### end Alembic commands ###
