"""create users table

Revision ID: f3dd71532bf5
Revises: aebf227c866a
Create Date: 2026-06-07 05:16:34.471643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3dd71532bf5'
down_revision: Union[str, Sequence[str], None] = 'aebf227c866a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=8), nullable=False))
    op.add_column('users', sa.Column('penname', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('introduction', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('personality', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('work', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'work')
    op.drop_column('users', 'personality')
    op.drop_column('users', 'introduction')
    op.drop_column('users', 'penname')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
